version: "3.9"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    
  redis:
    image: "redis:alpine"
  blogify-api:
    container_name: Blogify-API
    restart: always
    build:
      dockerfile: Dockerfile
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8009 --forwarded-allow-ips '*' --log-level debug
    ports:
      - 8009:8009
    depends_on:
      - mongodb
      - redis
  